/// <reference path="../../utils/ts-defs/behaviors/8 Direction/I8DirectionBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Anchor/IAnchorBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Bullet/IBulletBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Car/ICarBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Drag & Drop/IDragDropBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Fade/IFadeBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Flash/IFlashBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Follow/IFollowBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Jump-thru/IJumpthruBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Line of sight/ILOSBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Line of sight/ILOSBehaviorRay.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Move To/IMoveToBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Orbit/IOrbitBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Pathfinding/IPathfindingBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Pathfinding/IPathfindingMap.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Physics/IPhysicsBehavior.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Physics/IPhysicsBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Platform/IPlatformBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Rotate/IRotateBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Shadow caster/IShadowCasterBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Sine/ISineBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Solid/ISolidBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Tile movement/ITileMovementBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Timer/ITimerBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Turret/ITurretBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/behaviors/Tween/ITweenBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/editor/gfx/IDrawParams.d.ts" />
/// <reference path="../../utils/ts-defs/editor/gfx/IWebGLRenderer.d.ts" />
/// <reference path="../../utils/ts-defs/editor/gfx/IWebGLText.d.ts" />
/// <reference path="../../utils/ts-defs/editor/gfx/IWebGLTexture.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IBehaviorBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IBehaviorInfo.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IBehaviorInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IBehaviorTypeBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IPluginBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IPluginInfo.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IPluginProperty.d.ts" />
/// <reference path="../../utils/ts-defs/editor/ITypeBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/IWorldInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/editor/misc/IColor.d.ts" />
/// <reference path="../../utils/ts-defs/editor/misc/ILang.d.ts" />
/// <reference path="../../utils/ts-defs/editor/misc/IQuad.d.ts" />
/// <reference path="../../utils/ts-defs/editor/misc/IRect.d.ts" />
/// <reference path="../../utils/ts-defs/editor/misc/IZipFile.d.ts" />
/// <reference path="../../utils/ts-defs/editor/misc/IZipFileEntry.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/events/IEventBlock.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/events/IEventParentRow.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/events/IEventSheet.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/ILayer.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/ILayout.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/IProject.d.ts" />
/// <reference path="../../utils/ts-defs/editor/model/IProjectFile.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IAnimation.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IAnimationFrame.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IBehaviorType.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/ICollisionPoly.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IContainer.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IFamily.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IImagePoint.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IObjectClass.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IObjectInstance.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/editor/objects/IWorldInstance.d.ts" />
/// <reference path="../../utils/ts-defs/editor/sdk.d.ts" />
/// <reference path="../../utils/ts-defs/editor/ui/ILayoutView.d.ts" />
/// <reference path="../../utils/ts-defs/editor/ui/Util.d.ts" />
/// <reference path="../../utils/ts-defs/objects.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/3D camera/I3DCameraObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/3D shape/I3DShapeInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Advanced Random/IAdvancedRandomObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Array/IArrayInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Audio/IAudioObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Binary Data/IBinaryDataInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Button/IButtonInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/CSV/ICSVObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Dictionary/IDictionaryInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Drawing canvas/IDrawingCanvasInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Facebook/IFacebookObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/File chooser/IFileChooserInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/HTML Element/IHTMLElementInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/iframe/IIframeInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Internationalization/IInternationalizationObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/JSON/IJSONInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Keyboard/IKeyboardObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/List/IListInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Mouse/IMouseObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Multiplayer/IMultiplayerObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Multiplayer/IMultiplayerPeer.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Multiplayer/MultiplayerSignallingState.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Multiplayer/MultiplayerStats.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Particles/IParticlesInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Progress bar/IProgressBarInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/QR code/IQRCodeInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Shadow light/IShadowLightInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Slider bar/ISliderBarInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Sprite/ISpriteInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Sprite font/ISpriteFontInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/SVG Picture/ISVGPictureInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Text/ITextInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Text input/ITextInputInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Tiled Background/ITiledBackgroundInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Tilemap/ITilemapInstance.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Timeline controller/ITimelineControllerObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/plugins/Touch/ITouchObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/AddonSDK.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IAnimation.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IAnimationFrame.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IAssetManager.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IBehavior.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IBehaviorInstance.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IBehaviorType.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ICollisionEngine.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IDOMInstance.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IEffectInstance.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IFamily.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IImageInfo.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IInstance.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ILayer.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ILayout.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ILoopingConditionContext.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IObjectClass.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IObjectType.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IPlatformInfo.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IPlugin.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IRenderer.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IRendererText.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IRuntime.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKBehaviorBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKBehaviorInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKBehaviorTypeBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKDOMInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKDOMPluginBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKObjectTypeBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKPluginBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKUtils.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ISDKWorldInstanceBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IStorage.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ITexture.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ITimelineState.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ITimelineStateBase.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/ITweenState.d.ts" />
/// <reference path="../../utils/ts-defs/runtime/IWorldInstance.d.ts" />


export {}